apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
  labels:
    app: react-app
spec:
  replicas: 2  # Number of pods (adjust as needed)
  selector:
    matchLabels:
      app: react-app
  template:
    metadata:
      labels:
        app: react-app
    spec:
      containers:
        - name: react-app
          image: react-app:latest  # Name of the Docker image
          imagePullPolicy: Never    # Avoid pulling from the registry (use local image)
          ports:
            - containerPort: 80
