apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    app: react-app  # Must match the label in deployment.yaml
  ports:
    - protocol: TCP
      port: 80         # Port on the cluster
      targetPort: 80   # Port on the container
  type: NodePort       # Expose the service on a port accessible externally
