name: CI/CD Pipeline for Frontend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: [self-hosted, "MAYANK"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  deploy:
    name: Deploy to Docker
    needs: build
    runs-on: [self-hosted, "MAYANK"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Stop and Remove Old Docker Container
        shell: powershell
        run: |
          $container = docker ps -q -f "name=infinixmailboxfrontend"
          if ($container) {
              docker stop infinixmailboxfrontend
              Write-Host "Stopped running container."
          } else {
              Write-Host "No running container found to stop."
          }

          $container = docker ps -a -q -f "name=infinixmailboxfrontend"
          if ($container) {
              docker rm infinixmailboxfrontend
              Write-Host "Removed old container."
          } else {
              Write-Host "No container found to remove."
          }

      - name: Build Docker Image
        run: docker build -t infinixmailboxfrontend:latest .

      - name: Deploy New Docker Container
        run: docker run -d -p 80:80 --name infinixmailboxfrontend infinixmailboxfrontend:latest
