name: CI/CD Pipeline for Frontend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run tests
      - name: Run Tests
        run: npm test

      # Build the project
      - name: Build Project
        run: npm run build

      # Upload build artifacts (optional, useful if you want to store build files)
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: dist/

  deploy:
    name: Deploy to Docker
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Checkout code again
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker registry
      - name: Log in to Docker registry
        run: |
          echo ${{ secrets.DOCKER_USERNAME }} | docker login 192.168.1.216:5000 -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      # Build Docker image
      - name: Build Docker Image
        run: |
          docker build -t 192.168.1.216:5000/infinixmailboxfrontend:latest .

      # Push Docker image to local registry
      - name: Push Docker image to local registry
        run: |
          docker push 192.168.1.216:5000/infinixmailboxfrontend:latest

      # Deploy Docker container on local server (directly on local server)
      - name: Deploy Docker Container
        run: |
          # Pull the latest image from the registry
          docker pull 192.168.1.216:5000/infinixmailboxfrontend:latest
          
          # Stop and remove any previous container (if exists)
          docker stop infinixmailboxfrontend || true
          docker rm infinixmailboxfrontend || true
          
          # Run the new container on port 80
          docker run -d -p 80:80 --name infinixmailboxfrontend 192.168.1.216:5000/infinixmailboxfrontend:latest
          
          # Verify if the container is running
          docker ps
