
name: CI/CD Pipeline for Frontend

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: [self-hosted, "MAYANK"]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Upload Build Artifacts
        uses: - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: dist/

  deploy:
    name: Deploy to Docker
    needs: build  # Ensure 'deploy' depends on 'build'
    runs-on: [self-hosted, "MAYANK"]  # Use the self-hosted runner with the "MAYANK" label

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          # Build the Docker image locally and tag it as 'latest'
          docker build -t infinixmailboxfrontend:latest .

      - name: Stop and Remove Old Docker Container
        run: |
          # Check if the container exists and stop it if running
          if (docker ps -q -f "name=infinixmailboxfrontend") {
            docker stop infinixmailboxfrontend
          } else {
            Write-Host "No running container found to stop."
          }
          
          # Check if the container exists and remove it if present
          if (docker ps -a -q -f "name=infinixmailboxfrontend") {
            docker rm infinixmailboxfrontend
          } else {
            Write-Host "No container found to remove."
          }

      - name: Deploy New Docker Container
        run: |
          # Run the new container on port 80 (accessible via local IP)
          docker run -d -p 80:80 --name infinixmailboxfrontend infinixmailboxfrontend:latest
          # Verify if the container is running
          docker ps
